app/rokah_judge/models/problems.py
from rokah_judge import db
from datetime import datetime
from rokah_judge.models.testcases import Testcase


class Problem(db.Model):
    __tablename__ = "problems"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(50))
    text = db.Column(db.Text)
    time_limit = db.Column(db.Integer)
    memory_limit = db.Column(db.Integer)
    constraint = db.Column(db.Text)
    input = db.Column(db.Text)
    output = db.Column(db.Text)
    created_at = db.Column(db.DateTime)
    cases = db.relationship("Testcase", backref="problem", lazy=False)

    def __init__(
        self,
        title=None,
        text=None,
        time_limit=None,
        memory_limit=None,
        constraint=None,
        input=None,
        output=None,
        cases=None,
    ):
        self.title = title
        self.text = text
        self.time_limit = time_limit
        self.memory_limit = memory_limit
        self.constraint = constraint
        self.input = input
        self.output = output
        self.cases = cases
        self.created_at = datetime.utcnow()

    def __repr__(self):
        return "<Entry id:{} title:{} text:{} time_limit:{} memory_limit:{} constraint:{} input:{} output:{} sample:{}".format(
            self.id,
            self.title,
            self.text,
            self.time_limit,
            self.memory_limit,
            self.constraint,
            self.input,
            self.output,
            self.sample,
        )

app/rokah_judge/views/problems.py
import re
import glob
import zipfile
import os
from typing import DefaultDict
from flask_login.utils import login_required
from flask import request, redirect, url_for, render_template, flash, session
from rokah_judge.models.testcases import Testcase
from rokah_judge import db, app
from rokah_judge.utils.message import push
from rokah_judge.models.problems import Problem
from rokah_judge.models.submissions import Submission
from rokah_judge.models.languages import Language
from rokah_judge.utils.problem import unzip_problem, register_problem
from werkzeug.utils import secure_filename
from flask import Blueprint

problem = Blueprint("problem", __name__)


@problem.route("/problems/<int:id>", methods=["GET"])
@login_required
def show_problem(id):
    problem = Problem.query.get(id)
    samples = Testcase.query.filter(
        Testcase.problem_id == id, Testcase.is_sample).order_by(Testcase.id.desc()).all()
    languages = Language.query.order_by(Language.id.desc()).all()
    return render_template("problems/show.html", problem=problem, samples=samples, languages=languages)


@problem.route("/problems/", methods=["GET"])
@login_required
def show_problems():
    problems = Problem.query.order_by(Problem.id.desc()).all()
    return render_template("problems/list.html", problems=problems)


@problem.route("/problems/new", methods=["GET"])
@login_required
def new_problem():
    return render_template("problems/new.html")


@problem.route("/upload_problem", methods=["POST"])
def upload_problem():
    if request.method == "POST":
        files = request.files.getlist("file")
        os.makedirs(app.config["UPLOAD_FOLDER"], exist_ok=True)
        for file in files:
            filename = secure_filename(file.filename)
            file.save(os.path.join(app.config["UPLOAD_FOLDER"], filename))
            pdir = unzip_problem(os.path.join(
                app.config["UPLOAD_FOLDER"], filename))
            register_problem(pdir)
        flash("新しい問題が追加されました")
        return redirect(url_for("problem.show_problems"))


@problem.route("/problems/add", methods=["POST"])
@login_required
def add_problem():
    problem = Problem(
        title=request.form["title"],
        text=request.form["text"],
        time_limit=request.form["time_limit"],
        memory_limit=request.form["memory_limit"],
        constraint=request.form["constraint"],
        input=request.form["input"],
        output=request.form["output"],
    )
    db.session.add(problem)
    db.session.commit()
    flash("新しい問題が作成されました")
    return redirect(url_for("problem.show_problems"))


@problem.route("/problems/<int:id>/edit", methods=["GET"])
@login_required
def edit_problem(id):
    problem = Problem.query.get(id)
    cases = Testcase.query.filter(
        Testcase.problem_id == id).order_by(Testcase.id.desc()).all()
    return render_template("problems/edit.html", problem=problem, cases=cases)


@problem.route("/problems/<int:id>/update", methods=["POST"])
@login_required
def update_problem(id):
    problem = Problem.query.get(id)
    problem.title = request.form["title"]
    problem.text = request.form["text"]
    problem.time_limit = request.form["time_limit"]
    problem.memory_limit = request.form["memory_limit"]
    problem.constraint = request.form["constraint"]
    problem.input = request.form["input"]
    problem.output = request.form["output"]
    db.session.merge(problem)
    db.session.commit()

    case_indices = request.form.getlist("testcase_index[]")
    case_inputs = request.form.getlist("testcase_input[]")
    case_outputs = request.form.getlist("testcase_output[]")
    is_samples = request.form.getlist("is_sample")

    for id, input, output, is_sample in zip(case_indices, case_inputs, case_outputs, is_samples):
        if id == -1:
            case = Testcase("edit", input, output, is_sample)
        else:
            case = Testcase.query.get(id)
            case.input = input
            case.output = output
            case.is_sample = True if is_sample == '1' else False
            print(id)
            print(input)
            print(output)
            print(is_sample)
        db.session.merge(case)
        db.session.commit()
    flash("問題が更新されました")
    return redirect(url_for("problem.show_problems"))


@problem.route("/problems/<int:id>/delete", methods=["POST"])
@login_required
def delete_problem(id):
    problem = Problem.query.get(id)
    db.session.delete(problem)
    db.session.commit()
    flash("記事が削除されました")
    return redirect(url_for("problem.show_problems"))


@problem.route("/problems/<int:id>/submit", methods=["POST"])
@login_required
def submit(id):
    submission = Submission(
        problem_id=id,
        language=request.form["language"],
        code=request.form["code"],
        status="WJ",
        ac=0,
        wa=0,
        tle=0,
        re=0,
    )
    db.session.add(submission)
    db.session.commit()
    push(id=submission.id)
    flash("解答が提出されました")
    return redirect(url_for("submission.show_submissions"))

app/rokah_judge/templates/problems/edit.html
{% extends "layout.html" %}
{% block body %}
<form action="{{ url_for('problem.update_problem', id=problem.id) }}" method="POST" class="add-problem" novalidate>
    <div class="form-group">
        <label for="InputTitle">問題名</label>
        <input type="text" name="title" id="InputText" class="form-control" value="{{ problem.title }}" required>
        <div class="invalid-feedback">
            Please enter problem title.
        </div>
    </div>
    <div class="form-group">
        <label for="InputText">問題文</label>
        <textarea name="text" id="InputText" class="form-control" rows="10" required>{{ problem.text|safe }}</textarea>
        <div class="invalid-feedback">
            Please enter problem text.
        </div>
    </div>
    <div class="form-group">
        <label for="InputText">実行時間制限</label>
        <input type="text" name="time_limit" id="InputText" class="form-control" value="{{ problem.time_limit }}"
            required>
        <div class="invalid-feedback">
            Please enter time limit.
        </div>
    </div>
    <div class="form-group">
        <label for="InputText">メモリ制限</label>
        <input type="text" name="memory_limit" id="InputText" class="form-control" value="{{ problem.memory_limit }}"
            required>
        <div class="invalid-feedback">
            Please enter memory limit.
        </div>
    </div>
    <div class="form-group">
        <label for="InputText">制約</label>
        <textarea name="constraint" id="InputText" class="form-control" rows="5"
            required>{{ problem.constraint|safe }}</textarea>
        <div class="invalid-feedback">
            Please enter constraints.
        </div>
    </div>
    <div class="form-group">
        <label for="InputText">入力</label>
        <textarea name="input" id="InputText" class="form-control" rows="5" required>{{ problem.input|safe }}</textarea>
        <div class="invalid-feedback">
            Please enter problem input.
        </div>
    </div>
    <div class="form-group">
        <label for="InputText">出力</label>
        <textarea name="output" id="InputText" class="form-control" rows="5"
            required>{{ problem.output|safe }}</textarea>
        <div class="invalid-feedback">
            Please enter problem output.
        </div>
    </div>

    <div class="form-group">
        <label for="InputText">テストケース</label>
        <table>
            <thead>
                <tr>
                    <th>CaseID</th>
                    <th>Input</th>
                    <th>Output</th>
                    <th>IsSample</th>
                </tr>
            </thead>
            <tbody>
                {% for case in cases %}
                <tr>
                    <td><textarea name="testcase_index[]" class="form-control testcase_index" rows="5"
                            placeholder="-1">{{case.id}}</textarea></td>
                    <td><textarea name="testcase_input[]" class="form-control testcase_input" rows="5"
                            placeholder="入力">{{ case.content }}</textarea></td>
                    <td><textarea name="testcase_output[]" class="form-control testcase_output" rows="5"
                            placeholder="出力">{{ case.answer }}</textarea></td>
                    <td>
                        <div name="is_sample[]" class="is_sample">
                            <label class="custom-control custom-checkbox">
                                <input type="checkbox" name="is_sample" id="is_sample" value="1"
                                    class="custom-control-input">
                                <span class="custom-control-indicator"></span>
                                <span class="custom-control-description"></span>
                                サンプル
                            </label>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td>
                        <button type="button" id="btn-clone" class="btn btn-primary">追加</button>
                        <button type="button" id="btn-remove" class="btn btn-outline-danger">削除</button>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <button type="submit" class="btn btn-primary">更新</button>
</form>

<script>
    (function () {
        window.addEventListener('load', function () {
            var forms = document.getElementsByClassName('add-problem');
            var validation = Array.prototype.filter.call(forms, function (form) {
                form.addEventListener('submit', function (event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
</script>
<script src="{{ url_for('static', filename='js/edit.js') }}"></script>
{% endblock %}

app/rokah_judge/templates/problems/list.html
{% extends "layout.html" %}
{% block body %}
<ul class='list-group list-group-flush'>
    {% for problem in problems %}
    <div class="card">
        <img class="card-img-top" src="holder.js/100x180/" alt="">
        <div class="card-body">
            <h4 class="card-title"><a href="{{ url_for('problem.show_problem',id=problem.id) }}">{{ problem.title }}</a>
            </h4>
            <p class="card-text">{{ problem.time_limit }}sec / {{ problem.memory_limit }}MB</p>
        </div>
    </div>
    {% else %}
    問題がありません
    {% endfor %}
</ul>
{% endblock %}

app/rokah_judge/templates/problems/new.html
{% extends "layout.html" %}
{% block body %}
<link rel="stylesheet" href="{{ url_for('static', filename='problems/new.css') }}">

<form action="{{ url_for('problem.add_problem') }}" method="POST" class="add-problem" novalidate>
    <div class="form-group">
        <label for="InputTitle">問題名</label>
        <input type="text" name="title" id="InputText" class="form-control" required>
        <div class="invalid-feedback">
            Please enter problem title.
        </div>
    </div>
    <div class="form-group">
        <label for="InputText">問題文</label>
        <textarea name="text" id="InputText" class="form-control" rows="10" required></textarea>
        <div class="invalid-feedback">
            Please enter problem text.
        </div>
    </div>
    <div class="form-group">
        <label for="InputText">実行時間制限</label>
        <input type="text" name="time_limit" value="2" id="InputText" class="form-control" required>
        <div class="invalid-feedback">
            Please enter time limit.
        </div>
    </div>
    <div class="form-group">
        <label for="InputText">メモリ制限(MB)</label>
        <input type="text" name="memory_limit" value="256" id="InputText" class="form-control" required>
        <div class="invalid-feedback">
            Please enter memory limit.
        </div>
    </div>
    <div class="form-group">
        <label for="InputText">制約</label>
        <textarea name="constraint" id="InputText" class="form-control" rows="5" required></textarea>
        <div class="invalid-feedback">
            Please enter constraints.
        </div>
    </div>
    <div class="form-group">
        <label for="InputText">入力</label>
        <textarea name="input" id="InputText" class="form-control" rows="5" required></textarea>
        <div class="invalid-feedback">
            Please enter problem input.
        </div>
    </div>
    <div class="form-group">
        <label for="InputText">出力</label>
        <textarea name="output" id="InputText" class="form-control" rows="5" required></textarea>
        <div class="invalid-feedback">
            Please enter problem output.
        </div>
    </div>
    <div class="form-group">
        <label for="InputText">テストケース</label>
        <table>
            <thead>
                <tr>
                    <th>Input</th>
                    <th>Output</th>
                    <th>IsSample</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><textarea name="testcase_input[]" class="form-control testcase_input" rows="5"
                            placeholder="入力"></textarea></td>
                    <td><textarea name="testcase_output[]" class="form-control testcase_output" rows="5"
                            placeholder="出力"></textarea></td>
                    <td>
                        <div name="is_sample[]" class="is_sample">
                            <label class="custom-control custom-checkbox">
                                <input type="checkbox" id="is_sample" value="checkedValue" class="custom-control-input">
                                <span class="custom-control-indicator"></span>
                                <span class="custom-control-description"></span>
                                サンプル
                            </label>
                        </div>
                    </td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td>
                        <button type="button" id="btn-clone" class="btn btn-primary">追加</button>
                        <button type="button" id="btn-remove" class="btn btn-outline-danger">削除</button>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>


    <button type="submit" class="btn btn-primary">作成</button>
</form>

<form action="{{ url_for('problem.upload_problem') }}" method="POST" enctype="multipart/form-data">
    <input type="file" name="file" multiple="" />
    <input type="submit" />
</form>

<script src="{{ url_for('static', filename='js/new.js') }}"></script>

{% endblock %}

app/rokah_judge/templates/problems/show.html
{% extends "layout.html" %}
{% block body %}
<h2>{{ problem.title }}</h2>
<p>実行時間制限：{{ problem.time_limit }}sec / メモリ制限：{{ problem.memory_limit }}MB</p>
<br>
<h3>問題文</h3>
{{ problem.text|safe }}
<br>
<h3>制約</h3>
{{ problem.constraint|safe }}
<br>
<h3>入力</h3>
{{ problem.input|safe }}
<br>
<h3>出力</h3>
{{ problem.output|safe }}
<br>
{% for sample in samples %}
<h4>サンプル{{loop.index}}</h4>
<h5>入力</h5>
{{ sample.content|safe }}
<h5>出力</h5>
{{ sample.answer|safe }}
{% endfor %}
<br><br>
投稿日時{{ problem.created_at }}
<br>
<form action="{{ url_for('problem.submit', id=problem.id)}}" method=post class=submit>
    <select class="form-select" name=language aria-label="Select-language">
        <option selected>Select Language</option>
        {% for language in languages %}
        <option value="{{ language.name }}">{{ language.name }}</option>
        {% endfor %}
    </select>

    <div class="form-group">
        <label for="InputText">ソースコード</label>
        <textarea name=code id="InputText" class="form-control" placeholder="" aria-describedby="helpId"
            rows="20"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">提出</button>
</form>

<br><br>
<div class="btn-group">
    <form action="{{ url_for('problem.edit_problem', id=problem.id) }}" method="GET">
        <button type="submit" class="btn btn-primary">編集</button>
    </form>

    <form action="{{ url_for('problem.delete_problem', id=problem.id) }}" method="POST">
        <button type="submit" class="btn btn-danger" style="margin-left: 5px">削除</button>
    </form>
</div>

{% endblock %}