app/rokah_judge/views/auth.py
from flask import request, redirect, url_for, render_template, flash, session, Blueprint
from flask_login.utils import login_required, login_user, logout_user
from rokah_judge import db
from rokah_judge.models.users import User
from werkzeug.security import generate_password_hash, check_password_hash
from functools import wraps

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET"])
def login():
    return render_template("login.html")


@auth.route("/login", methods=["POST"])
def login_post():
    email = request.form.get("email")
    password = request.form.get("password")
    remember = True if request.form.get("remember") else False

    user = User.query.filter_by(email=email).first()

    if not user or not check_password_hash(user.password, password):
        flash("Please check your email or password and try again.")
        return redirect(url_for("auth.login"))

    login_user(user, remember=remember)
    return redirect(url_for("view.top", _external=True))


@auth.route("/signup", methods=["GET"])
def signup():
    return render_template("signup.html")


@auth.route("/signup", methods=["POST"])
def signup_post():
    email = request.form.get("email")
    name = request.form.get("name")
    password = request.form.get("password")
    user = User.query.filter_by(email=email).first()

    if user:  # already exists
        flash("すでに使用されているメールアドレスです！")
        return redirect(url_for("auth.signup"))

    new_user = User(
        email=email,
        name=name,
        password=generate_password_hash(password, method="sha256"),
    )

    db.session.add(new_user)
    db.session.commit()
    flash("ユーザー登録が完了しました！")
    return redirect(url_for("auth.login"))


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    flash("ログアウトしました")
    return redirect(url_for("view.top"))


@auth.errorhandler(404)
def non_existant_route(error):
    return redirect(url_for("auth.login"))

app/rokah_judge/views/problems.py
import re
import glob
import zipfile
import os
from typing import DefaultDict
from flask_login.utils import login_required
from flask import request, redirect, url_for, render_template, flash, session
from rokah_judge.models.testcases import Testcase
from rokah_judge import db, app
from rokah_judge.utils.message import push
from rokah_judge.models.problems import Problem
from rokah_judge.models.submissions import Submission
from rokah_judge.models.languages import Language
from rokah_judge.utils.problem import unzip_problem, register_problem
from werkzeug.utils import secure_filename
from flask import Blueprint

problem = Blueprint("problem", __name__)


@problem.route("/problems/<int:id>", methods=["GET"])
@login_required
def show_problem(id):
    problem = Problem.query.get(id)
    samples = Testcase.query.filter(
        Testcase.problem_id == id, Testcase.is_sample).order_by(Testcase.id.desc()).all()
    languages = Language.query.order_by(Language.id.desc()).all()
    return render_template("problems/show.html", problem=problem, samples=samples, languages=languages)


@problem.route("/problems/", methods=["GET"])
@login_required
def show_problems():
    problems = Problem.query.order_by(Problem.id.desc()).all()
    return render_template("problems/list.html", problems=problems)


@problem.route("/problems/new", methods=["GET"])
@login_required
def new_problem():
    return render_template("problems/new.html")


@problem.route("/upload_problem", methods=["POST"])
def upload_problem():
    if request.method == "POST":
        files = request.files.getlist("file")
        os.makedirs(app.config["UPLOAD_FOLDER"], exist_ok=True)
        for file in files:
            filename = secure_filename(file.filename)
            file.save(os.path.join(app.config["UPLOAD_FOLDER"], filename))
            pdir = unzip_problem(os.path.join(
                app.config["UPLOAD_FOLDER"], filename))
            register_problem(pdir)
        flash("新しい問題が追加されました")
        return redirect(url_for("problem.show_problems"))


@problem.route("/problems/add", methods=["POST"])
@login_required
def add_problem():
    problem = Problem(
        title=request.form["title"],
        text=request.form["text"],
        time_limit=request.form["time_limit"],
        memory_limit=request.form["memory_limit"],
        constraint=request.form["constraint"],
        input=request.form["input"],
        output=request.form["output"],
    )
    db.session.add(problem)
    db.session.commit()
    flash("新しい問題が作成されました")
    return redirect(url_for("problem.show_problems"))


@problem.route("/problems/<int:id>/edit", methods=["GET"])
@login_required
def edit_problem(id):
    problem = Problem.query.get(id)
    cases = Testcase.query.filter(
        Testcase.problem_id == id).order_by(Testcase.id.desc()).all()
    return render_template("problems/edit.html", problem=problem, cases=cases)


@problem.route("/problems/<int:id>/update", methods=["POST"])
@login_required
def update_problem(id):
    problem = Problem.query.get(id)
    problem.title = request.form["title"]
    problem.text = request.form["text"]
    problem.time_limit = request.form["time_limit"]
    problem.memory_limit = request.form["memory_limit"]
    problem.constraint = request.form["constraint"]
    problem.input = request.form["input"]
    problem.output = request.form["output"]
    db.session.merge(problem)
    db.session.commit()

    case_indices = request.form.getlist("testcase_index[]")
    case_inputs = request.form.getlist("testcase_input[]")
    case_outputs = request.form.getlist("testcase_output[]")
    is_samples = request.form.getlist("is_sample")

    for id, input, output, is_sample in zip(case_indices, case_inputs, case_outputs, is_samples):
        if id == -1:
            case = Testcase("edit", input, output, is_sample)
        else:
            case = Testcase.query.get(id)
            case.input = input
            case.output = output
            case.is_sample = True if is_sample == '1' else False
            print(id)
            print(input)
            print(output)
            print(is_sample)
        db.session.merge(case)
        db.session.commit()
    flash("問題が更新されました")
    return redirect(url_for("problem.show_problems"))


@problem.route("/problems/<int:id>/delete", methods=["POST"])
@login_required
def delete_problem(id):
    problem = Problem.query.get(id)
    db.session.delete(problem)
    db.session.commit()
    flash("記事が削除されました")
    return redirect(url_for("problem.show_problems"))


@problem.route("/problems/<int:id>/submit", methods=["POST"])
@login_required
def submit(id):
    submission = Submission(
        problem_id=id,
        language=request.form["language"],
        code=request.form["code"],
        status="WJ",
        ac=0,
        wa=0,
        tle=0,
        re=0,
    )
    db.session.add(submission)
    db.session.commit()
    push(id=submission.id)
    flash("解答が提出されました")
    return redirect(url_for("submission.show_submissions"))

app/rokah_judge/templates/layout.html
<!DOCTYPE html>
<title>Rokah Judge</title>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"
    integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js"
    integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj"
    crossorigin="anonymous"></script>

<script type="text/x-mathjax-config">
  MathJax.Hub.Config({ tex2jax: { inlineMath: [['$','$'], ["\\(","\\)"]] } });
</script>
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML">
</script>
<meta http-equiv="X-UA-Compatible" CONTENT="IE=EmulateIE7" />

<!-- jQurry -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/styles/vs.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>

<link href="https://fonts.googleapis.com/earlyaccess/mplus1p.css" rel="stylesheet" type="text/css">
<link rel=stylesheet href="{{ url_for('static', filename='style.css') }}">
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('view.top') }}">rokah judge</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    {% if not current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">ログイン</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.signup') }}">サインアップ</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('problem.show_problems') }}">問題一覧</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('submission.show_submissions') }}">提出一覧</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('problem.new_problem') }}">問題作成</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">ログアウト</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% for message in get_flashed_messages() %}
    <div class="alert alert-info" role="alert">
        {{ message }}
    </div>
    {% endfor %}

    <div class="blog-body">
        {% block body %}{% endblock %}
    </div>
</div>

app/rokah_judge/templates/login.html
{% extends "layout.html" %}
{% block body %}
<!-- <form action="{{ url_for('auth.login') }}" method=POST>
  <div class="form-group">
    <label for="InputTitle">ユーザ名</label>
    <input type="text" name="username" id="InputTitle" class="form-control" placeholder="" aria-describedby="helpId">
  </div>
  <div class="form-group">
    <label for="InputPassword">パスワード</label>
    <input type="password" name="password" id="InputPassword" class="form-control" placeholder=""
      aria-describedby="helpId">
  </div>
  <button type="submit" class="btn btn-primary">ログイン</button>
</form> -->
<div class="column is-4 is-offset-4">
  <h3 class="title">Login</h3>
  <div class="box">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="notification is-danger">
      {{ messages[0] }}
    </div>
    {% endif %}
    {% endwith %}
    <form method="POST" action="/login">
      <div class="field">
        <div class="control">
          <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
        </div>
      </div>

      <div class="field">
        <div class="control">
          <input class="input is-large" type="password" name="password" placeholder="Your Password">
        </div>
      </div>
      <div class="field">
        <label class="checkbox">
          <input type="checkbox">
          Remember me
        </label>
      </div>
      <button class="button is-block is-info is-large is-fullwidth">Login</button>
    </form>
  </div>
</div>
{% endblock %}

app/rokah_judge/templates/signup.html
{% extends "layout.html" %}

{% block body %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="notification is-danger">
            {{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
        </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/signup">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}

app/rokah_judge/templates/top.html
{% extends "layout.html" %}
{% block body %}
Hello! rokah judge!
{% endblock %}